export interface themTour {
    idTour: string,
    tenTour: string,
    loaiTour: string,
    phuongTienDiChuyen: string,
    moTa: string,
    soLuongNguoiLon: string,
    soLuongTreEm: string,
    thoiGianBatDau: Date,
    thoiGianKetThuc: Date,
    noiKhoiHanh: string,
    soChoConNhan: string,
    idDoiTac: string,
    giaTreEm: string,
    giaNguoiLon: string,
    ngayThem: Date,
    dichVuDiKem?: string,
    tinhTrang: string,
    imgSelected: any,
}